import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import StoreProvider from "./StoreProvider";
import DefaultValues from "@/components/defaultValues/DefaultValues";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <DefaultValues/>
          <Header />
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
